---
Title: Conhecendo o LabHab
---

# O surgimento do LabHab

Criado em novembro de 1996, no Departamento de Projeto da Faculdade de Arquitetura e Urbanismo e de Design (FAU-USP), o Laboratório de Habitação e Assentamentos Humanos (LabHab) iniciou suas atividades em março de 1997, com o propósito de integrar ensino, pesquisa e extensão universitária para abordar as demandas habitacionais, urbanas e ambientais no contexto da histórica desigualdade social e territorial brasileira. Suas atividades têm um caráter experimental, proporcionando formação e capacitação para análise crítica e ação propositiva.

O LabHab realiza diversas atividades com o suporte financeiro da própria USP, entidades nacionais e internacionais como FAPESP, FINEP, CNPq, CEF e programas de Cooperação Internacional, como GIZ. Contando com uma equipe regular de professores e estudantes, além de um grupo mais amplo de pesquisadores associados, o Laboratório fomenta debates, seminários temáticos e pesquisas interdisciplinares, incluindo profissionais e estudantes de diversas áreas. Com enfoque interdisciplinar, o LabHab propicia colaborações intradepartamentais e interdepartamentais na FAU-USP, interunidades na USP e em outras instituições nacionais e internacionais, visando cumprir seus objetivos em consonância com as diretrizes da FAU-USP.


# Atuação

O LabHab articula ensino, pesquisa e extensão para criar um ambiente acadêmico fundamentado na realidade social. Os projetos desenvolvidos – de assessoria e de pesquisa – estão alinhados com disciplinas ministradas pelo grupo de professores e busca explorar a produção social do espaço urbano abordando temas como financiamento, papel do Estado e do mercado, ATHIS, produção imobiliária, entre outros.

No âmbito da pesquisa, o LabHab oferece suporte a trabalhos acadêmicos em diversos níveis, desde TFG e Iniciação Científica até Pós-Doutorado. Na extensão, foca na construção de conhecimento e qualificação de diversos atores, promovendo o direito à cidade e à moradia, orientada pela construção conjunta de conhecimento.

O LabHab está comprometido com a formação de novos profissionais para lidar com os desafios urbanos no Brasil e na América Latina, onde a maior parte do espaço é produzida sem intervenção profissional. Reconhecendo a importância da extensão como pesquisa e prática de aprendizado, o LabHab colabora com instituições similares no país e no exterior, implementando diversas formas de trabalho, incluindo pesquisa, seminários, oficinas e assessoria a planos e projetos associados à capacitação.


# Produtos

A partir das atividades realizadas pelo LabHab, diferentes tipos de produtos vêm sendo gerados ao longo do tempo. Visando a geração de subsídios para embasar e estimular a criação, o monitoramento e o aperfeiçoamento das políticas públicas, relatórios, seminários, cursos de capacitação e debates são alguns dos exemplos. Os produtos estão disponíveis na sede do laboratório, em seu [website](https://www.labhab.fau.usp.br/biblioteca/) e na biblioteca da FAU-USP.

Destaque-se, ainda, que a geração e a disponibilização desses produtos também servem como fundamento para a ação imediata de associações de moradores, movimentos sociais e funcionários públicos, para além de fomentar um importante e necessário espaço de aprendizado para estudantes de graduação e pós-graduação. Dessa forma, o LabHab busca reunir agentes públicos, sociedade civil organizada, pesquisadores e militantes em prol da justiça socioambiental, em um processo de contínuo aprimoramento e desenvolvimento, sendo um espaço de aprendizado para todos ao longo de seus mais de 25 anos de atividades.

Conheça alguns dos produtos na  [biblioteca](https://www.labhab.fau.usp.br/biblioteca/) do laboratório.